/**
 * The SQLite arm — a device's answer to each question, and the reason it is the right one.
 *
 * Two of these are no-ops, and a no-op is the most dangerous thing this file can contain: it
 * compiles, it runs, and it protects nothing. Both are safe for the SAME structural reason and it
 * is written beside each rather than assumed — the engine store is reached through ONE serialized
 * connection. There is no second writer to exclude, and a second connection to the same file does
 * not contend for rows, it fails outright. So the ordering the server buys with locks is already
 * true here by construction, and adding a lock would be a second mechanism guarding nothing.
 *
 * The rest are real translations, and the two that change meaning are named: text search moves
 * from a generated tsvector to an external-content full-text index, and case-insensitive matching
 * is folded explicitly because this dialect's own `like` folds ASCII only.
 */
import { sql, type SQL } from "drizzle-orm";
import { assertComparable } from "./index.js";
import type { Dialect, LockOptions, SearchArm, SearchCorpus } from "./index.js";

/**
 * The oldest SQLite this schema can be opened on, and what each digit buys.
 *
 * Stated as three separate reasons rather than one number so a future reader can tell which
 * feature a bump would be for: `RETURNING` arrived in 3.35, window functions — which the ranked
 * reads use in place of the server's `DISTINCT ON` — in 3.25, sub-second `unixepoch` in 3.42, and
 * `octet_length`, which a CHECK in the schema itself uses, in 3.43. The highest of the FOUR is the
 * floor, and it is 3.43.
 */
export const SQLITE_MINIMUM = {
  returning: "3.35.0", unixepochSubsec: "3.42.0", windowFunctions: "3.25.0",
  /** `octet_length`, which a CHECK in the schema itself uses — the highest of the four. */
  octetLength: "3.43.0",
} as const;

/** The floor as a comparable tuple: the highest of the four requirements above. */
const MINIMUM_TUPLE = [3, 43, 0] as const;

function versionTuple(version: string): [number, number, number] {
  const parts = version.split(".").map((n) => Number.parseInt(n, 10));
  return [parts[0] ?? 0, parts[1] ?? 0, parts[2] ?? 0];
}

/**
 * Refuse a build of SQLite that cannot run this schema, BEFORE the first statement.
 *
 * The alternative is discovering it from a syntax error inside a drain, which names a query and
 * not the library — and full-text search is worse than that, because a build without it fails only
 * when somebody searches, long after the store was written.
 */
export function assertSqliteCapabilities(probe: { version: string; compileOptions: readonly string[] }): void {
  const [major, minor, patch] = versionTuple(probe.version);
  const [minMajor, minMinor, minPatch] = MINIMUM_TUPLE;
  const tooOld = major < minMajor
    || (major === minMajor && (minor < minMinor || (minor === minMinor && patch < minPatch)));
  if (tooOld) {
    throw new Error(
      `this store needs SQLite ${minMajor}.${minMinor}.${minPatch} or newer and found ${probe.version}: ` +
        `RETURNING needs ${SQLITE_MINIMUM.returning}, unixepoch('subsec') needs ` +
        `${SQLITE_MINIMUM.unixepochSubsec}, window functions need ${SQLITE_MINIMUM.windowFunctions}, ` +
        `octet_length needs ${SQLITE_MINIMUM.octetLength}.`,
    );
  }
  if (!probe.compileOptions.some((o) => o.toUpperCase().includes("ENABLE_FTS5"))) {
    throw new Error(
      "this build of SQLite has no FTS5, so the mail index cannot be built. Searching would " +
        "return nothing on a store that looks complete, which is why this refuses at open time " +
        "rather than at the first query.",
    );
  }
}

/** Milliseconds since the epoch, which is how every timestamp column stores an instant here. */
const NOW_MS = sql`CAST(unixepoch('subsec') * 1000 AS INTEGER)`;

/**
 * Announcements for a program that is its own only listener.
 *
 * The server's notification crosses connections; this one cannot and does not pretend to. On a
 * device the writer and the reader are the same process, so an in-process emitter delivers to the
 * whole audience — and a caller that assumed otherwise would be assuming a second process that is
 * not there.
 */
type ChannelListener = (payload: string) => void;
const listeners = new Map<string, Set<ChannelListener>>();

/** Listen for local announcements on a channel. Returns the function that stops listening. */
export function onLocalNotify(channel: string, listener: ChannelListener): () => void {
  const set = listeners.get(channel) ?? new Set<ChannelListener>();
  set.add(listener);
  listeners.set(channel, set);
  return () => { set.delete(listener); };
}

export function sqliteDialect(): Dialect {
  return {
    name: "sqlite",

    now: () => NOW_MS,
    ts: (at: Date) => sql`${at.getTime()}`,

    castInt: (v) => sql`CAST(${v} AS INTEGER)`,
    castText: (v) => sql`CAST(${v} AS TEXT)`,
    // Identifiers are text here and are generated by the application on both dialects, so this is
    // a widening to the storage type rather than a conversion.
    castUuid: (v) => sql`CAST(${v} AS TEXT)`,
    // JSON is stored as text and read back through the JSON functions, so the cast is to text and
    // the shape is the caller's business, exactly as it is on the server.
    castJsonb: (v) => sql`CAST(${v} AS TEXT)`,

    // See the header: one serialized connection is the ordering guarantee, so there is nothing
    // for a row lock to add.
    forUpdate: <Q>(q: Q, _opts?: LockOptions): Q => q,
    skipLocked: <Q>(q: Q, _opts?: Omit<LockOptions, "skipLocked">): Q => q,
    advisoryLock: async () => {},

    notify: async (_tx, channel, payload) => {
      for (const listener of listeners.get(channel) ?? []) listener(payload);
    },

    // Folded on both sides so the comparison is at least symmetric — but NOT equivalent to the
    // server's, and the difference is worth knowing before it is relied on: this store's `lower()`
    // folds ASCII and nothing else, so `Ä` and `ä` remain distinct here and do not on Postgres. A
    // search for a name in any other alphabet therefore matches less on a device. Closing that gap
    // needs a folded column or an ICU build, neither of which this store has; naming it is what
    // stops the next reader assuming the two are the same comparison.
    /**
     * `trim(X, Y)` removes any of Y's characters from both ends, so what is left is empty exactly
     * when every character of X was one of them — the same question the server's regex asks, put
     * the only way this store can ask it. The class is built with `char()` rather than written as
     * escapes because this store's string literals do not interpret backslash escapes at all: a
     * literal '\t' here is a backslash and a t, and the predicate would then trim neither tabs nor
     * anything else it was meant to.
     */
    hasNonBlank: (column) =>
      sql`trim(coalesce(${column}, ''), ' ' || char(9) || char(10) || char(13) || char(12) || char(11)) <> ''`,

    ilike: (column, pattern) => sql`lower(${column}) like lower(${pattern})`,

    interval: (ms: number) => sql`${Math.trunc(ms)}`,

    /**
     * `max`, and the argument count is load-bearing.
     *
     * This store gives ONE name to two different things: `max(a, b)` compares values within a
     * row, `max(a)` is the aggregate over a result set. A single-argument call would therefore
     * run and answer a different question — collapsing the rows instead of comparing — with no
     * error anywhere. The contract refuses it, and this is the arm that would have suffered.
     */
    greatest: (...values) => {
      assertComparable(values.length);
      return sql`max(${sql.join(values.map((v) => sql`${v}`), sql`, `)})`;
    },

    // Arguments in the opposite order to the server's syntax, which is the whole reason this is
    // a member rather than a shared spelling.
    strpos: (hay, needle) => sql`instr(${hay}, ${needle})`,

    substr: (x, from, length) => (length === undefined
      ? sql`substr(${x}, ${from})`
      : sql`substr(${x}, ${from}, ${length})`),

    /** As the server's, and for the same reason: an array is one parameter, not a list. */
    jsonHasAny: (column, keys) => {
      if (keys.length === 0) return sql`0`;
      const members = keys.map((k) => sql`${k}`);
      return sql`EXISTS (
        SELECT 1 FROM json_each(${column}) WHERE json_each.key IN (${sql.join(members, sql`, `)})
      )`;
    },

    exec: async (db, statement) => {
      const handle = db as { all?: (s: SQL) => Promise<unknown[]>; run?: (s: SQL) => Promise<unknown> };
      if (typeof handle.all === "function") {
        const rows = await handle.all(statement);
        return rows.map((r) => (Array.isArray(r) ? r : Object.values(r as object)));
      }
      await handle.run?.(statement);
      return [];
    },

    search: {
      // Full-text lives in external-content tables kept beside the rows by triggers, rather than
      // in a generated column on the row itself: this dialect has no stored generated column of
      // that kind, and duplicating the text into the row would double what a mailbox costs on a
      // device. `bm25` returns a smaller number for a better match, so it is negated to rank the
      // same direction the server's does.
      //
      // The knowledge base has its own table and no alias — its caller selects `from kb_entries`
      // with nothing else in the statement — so `rowid` there is unqualified, while the mail
      // corpus qualifies against the `m` and `b` its caller joins.
      lexical: (q: string, corpus: SearchCorpus): SearchArm => {
        if (corpus === "kb") {
          return {
            pred: sql`rowid IN (SELECT rowid FROM kb_entries_fts WHERE kb_entries_fts MATCH ${q})`,
            rank: sql`-COALESCE((SELECT bm25(kb_entries_fts) FROM kb_entries_fts WHERE kb_entries_fts MATCH ${q} AND rowid = kb_entries.rowid), 0)`,
          };
        }
        return {
          pred: sql`(m.rowid IN (SELECT rowid FROM messages_fts WHERE messages_fts MATCH ${q})
                  or b.rowid IN (SELECT rowid FROM message_bodies_fts WHERE message_bodies_fts MATCH ${q}))`,
          rank: sql`-COALESCE((SELECT bm25(messages_fts) FROM messages_fts WHERE messages_fts MATCH ${q} AND rowid = m.rowid), 0)`,
        };
      },
      fuzzy: (q: string, corpus: SearchCorpus, _opts): SearchArm => {
        // There is no trigram index to have, so this is the degrade the server also falls back to
        // — one shape on both dialects rather than a device-only third behaviour.
        const like = `%${q}%`;
        if (corpus === "kb") {
          return {
            pred: sql`(lower(title) like lower(${like}) or lower(content) like lower(${like}))`,
            rank: sql`0`,
          };
        }
        return {
          pred: sql`(lower(m.subject) like lower(${like}) or lower(m.from_address) like lower(${like}))`,
          // RECENCY, as the server's degrade ranks. The instant is already a count of
          // milliseconds in this store, so there is no epoch to extract — the column IS the
          // number, and `extract(epoch …)` would not parse here at all.
          rank: sql`coalesce(m.date, 0)`,
        };
      },
    },
  };
}
