/**
 * The SQLite arm — a device's answer to each question, and the reason it is the right one.
 *
 * Two of these are no-ops, and a no-op is the most dangerous thing this file can contain: it
 * compiles, it runs, and it protects nothing. Both are safe for the SAME structural reason and it
 * is written beside each rather than assumed — the engine store is reached through ONE serialized
 * connection. There is no second writer to exclude, and a second connection to the same file does
 * not contend for rows, it fails outright. So the ordering the server buys with locks is already
 * true here by construction, and adding a lock would be a second mechanism guarding nothing.
 *
 * The rest are real translations, and the two that change meaning are named: text search moves
 * from a generated tsvector to an external-content full-text index, and case-insensitive matching
 * is folded explicitly because this dialect's own `like` folds ASCII only.
 */
import { sql, type SQL } from "drizzle-orm";
import type { Dialect, LockOptions, SearchArm } from "./index.js";

/**
 * The oldest SQLite this schema can be opened on, and what each digit buys.
 *
 * Stated as three separate reasons rather than one number so a future reader can tell which
 * feature a bump would be for: `RETURNING` arrived in 3.35, sub-second `unixepoch` in 3.42, and
 * window functions — which the ranked reads use in place of the server's `DISTINCT ON` — in 3.25.
 * The highest of the three is the floor.
 */
export const SQLITE_MINIMUM = { returning: "3.35.0", unixepochSubsec: "3.42.0", windowFunctions: "3.25.0" } as const;

/** The floor as a comparable tuple: the highest of the three requirements above. */
const MINIMUM_TUPLE = [3, 42, 0] as const;

function versionTuple(version: string): [number, number, number] {
  const parts = version.split(".").map((n) => Number.parseInt(n, 10));
  return [parts[0] ?? 0, parts[1] ?? 0, parts[2] ?? 0];
}

/**
 * Refuse a build of SQLite that cannot run this schema, BEFORE the first statement.
 *
 * The alternative is discovering it from a syntax error inside a drain, which names a query and
 * not the library — and full-text search is worse than that, because a build without it fails only
 * when somebody searches, long after the store was written.
 */
export function assertSqliteCapabilities(probe: { version: string; compileOptions: readonly string[] }): void {
  const [major, minor, patch] = versionTuple(probe.version);
  const [minMajor, minMinor, minPatch] = MINIMUM_TUPLE;
  const tooOld = major < minMajor
    || (major === minMajor && (minor < minMinor || (minor === minMinor && patch < minPatch)));
  if (tooOld) {
    throw new Error(
      `this store needs SQLite ${minMajor}.${minMinor}.${minPatch} or newer and found ${probe.version}: ` +
        `RETURNING needs ${SQLITE_MINIMUM.returning}, unixepoch('subsec') needs ` +
        `${SQLITE_MINIMUM.unixepochSubsec}, window functions need ${SQLITE_MINIMUM.windowFunctions}.`,
    );
  }
  if (!probe.compileOptions.some((o) => o.toUpperCase().includes("ENABLE_FTS5"))) {
    throw new Error(
      "this build of SQLite has no FTS5, so the mail index cannot be built. Searching would " +
        "return nothing on a store that looks complete, which is why this refuses at open time " +
        "rather than at the first query.",
    );
  }
}

/** Milliseconds since the epoch, which is how every timestamp column stores an instant here. */
const NOW_MS = sql`CAST(unixepoch('subsec') * 1000 AS INTEGER)`;

/**
 * Announcements for a program that is its own only listener.
 *
 * The server's notification crosses connections; this one cannot and does not pretend to. On a
 * device the writer and the reader are the same process, so an in-process emitter delivers to the
 * whole audience — and a caller that assumed otherwise would be assuming a second process that is
 * not there.
 */
type ChannelListener = (payload: string) => void;
const listeners = new Map<string, Set<ChannelListener>>();

/** Listen for local announcements on a channel. Returns the function that stops listening. */
export function onLocalNotify(channel: string, listener: ChannelListener): () => void {
  const set = listeners.get(channel) ?? new Set<ChannelListener>();
  set.add(listener);
  listeners.set(channel, set);
  return () => { set.delete(listener); };
}

export function sqliteDialect(): Dialect {
  return {
    name: "sqlite",

    now: () => NOW_MS,
    ts: (at: Date) => sql`${at.getTime()}`,

    castInt: (v) => sql`CAST(${v} AS INTEGER)`,
    castText: (v) => sql`CAST(${v} AS TEXT)`,
    // Identifiers are text here and are generated by the application on both dialects, so this is
    // a widening to the storage type rather than a conversion.
    castUuid: (v) => sql`CAST(${v} AS TEXT)`,
    // JSON is stored as text and read back through the JSON functions, so the cast is to text and
    // the shape is the caller's business, exactly as it is on the server.
    castJsonb: (v) => sql`CAST(${v} AS TEXT)`,

    // See the header: one serialized connection is the ordering guarantee, so there is nothing
    // for a row lock to add.
    forUpdate: <Q>(q: Q, _opts?: LockOptions): Q => q,
    skipLocked: <Q>(q: Q, _opts?: Omit<LockOptions, "skipLocked">): Q => q,
    advisoryLock: async () => {},

    notify: async (_tx, channel, payload) => {
      for (const listener of listeners.get(channel) ?? []) listener(payload);
    },

    // `like` here folds ASCII only, so a subject in any other alphabet would match by accident of
    // encoding. Folding both sides explicitly makes the comparison mean what the server's does.
    ilike: (column, pattern) => sql`lower(${column}) like lower(${pattern})`,

    interval: (ms: number) => sql`${Math.trunc(ms)}`,

    jsonHasAny: (column, keys) => sql`EXISTS (
      SELECT 1 FROM json_each(${column}) WHERE json_each.key IN ${keys}
    )`,

    exec: async (db, statement) => {
      const handle = db as { all?: (s: SQL) => Promise<unknown[]>; run?: (s: SQL) => Promise<unknown> };
      if (typeof handle.all === "function") return handle.all(statement);
      await handle.run?.(statement);
      return [];
    },

    search: {
      // Full-text lives in external-content tables kept beside the rows by triggers, rather than
      // in a generated column on the row itself: this dialect has no stored generated column of
      // that kind, and duplicating the text into the row would double what a mailbox costs on a
      // device. `bm25` returns a smaller number for a better match, so it is negated to rank the
      // same direction the server's does.
      lexical: (q: string): SearchArm => ({
        pred: sql`(m.rowid IN (SELECT rowid FROM messages_fts WHERE messages_fts MATCH ${q})
                or b.rowid IN (SELECT rowid FROM message_bodies_fts WHERE message_bodies_fts MATCH ${q}))`,
        rank: sql`-COALESCE((SELECT bm25(messages_fts) FROM messages_fts WHERE messages_fts MATCH ${q} AND rowid = m.rowid), 0)`,
      }),
      fuzzy: (q: string, _opts): SearchArm => {
        // There is no trigram index to have, so this is the degrade the server also falls back to
        // — one shape on both dialects rather than a device-only third behaviour.
        const like = `%${q}%`;
        return {
          pred: sql`(lower(m.subject) like lower(${like}) or lower(m.from_address) like lower(${like}))`,
          rank: sql`0`,
        };
      },
    },
  };
}
