-- ENFORCED SYNC — "this mailbox owes a reconcile now", stamped by the API and cleared by the worker.
--
-- ══ WHAT THIS FIXES ════════════════════════════════════════════════════════════════════════
--
-- The sync worker runs a cycle every pollIntervalMs (60 s) and takes an IDLE push when the server
-- offers one. That is the right cadence for mail arriving on its own, and the wrong one for a change
-- the USER just made and is looking at: a message they sent, whose Sent-folder copy has to show up
-- in their own mirror; a folder move whose desired state the mirror should reflect. Up to a minute of
-- "I did that / I still cannot see it" is the whole of the gap.
--
-- The API stamps `sync_requested_at = now()` the instant it finalizes such a write. A short worker
-- scan (sync-kick, ~3 s) picks up any stamped mailbox IT SERVES, triggers an out-of-band cycle, and
-- clears the stamp — so the user-visible reconcile happens in seconds instead of at the next poll.
--
-- ══ IT IS A DOORBELL, NOT STATE ════════════════════════════════════════════════════════════
--
-- NULL is the resting state (nothing owed). A timestamp means "a user-visible write landed then;
-- reconcile and clear". Nothing reads it to make a routing decision. The worker clears COMPARE-AND-
-- CLEAR — only the exact value it observed — so a second stamp that lands while a kick is running is
-- not lost; the clear misses and the next scan re-kicks. A burst collapses to at most one extra cycle.
--
-- ══ ADDITIVE, IDEMPOTENT, NO CHECK ═════════════════════════════════════════════════════════
--
-- `ADD COLUMN IF NOT EXISTS`, nullable, no default: a catalog-only change, a replay is a no-op, and a
-- partially-applied window costs nothing (an unstamped mailbox is exactly today's poll-only
-- behaviour). No CHECK — a timestamp closes no set, the same reasoning as `sensitive_rescreen_at` and
-- `retry_after` one migration family over. `ADD COLUMN` inherits the table's grants.
--
-- ══ COMPATIBILITY AND DEPLOY ORDER ═════════════════════════════════════════════════════════
--
-- Order is migration → API → worker, and neither arrow is load-bearing for correctness, only for not
-- wasting a deploy: an API deployed ahead of the column would fail the stamp write, which is a
-- best-effort write beside the send/move finalize and must never fail the user's action — so the
-- stamp is caught and logged, never fatal. A worker deployed behind the migration simply finds
-- nothing stamped and polls as it always has. `MailboxService.list` selects whole rows, so
-- `["mailboxes","sync_requested_at"]` joins the mail schema markers for a clean 503 on a too-early API.
--
-- ROLLBACK is `ALTER TABLE mailboxes DROP COLUMN sync_requested_at`; the cost is a return to
-- poll-only latency for user-visible writes. No data is lost — the column holds a transient doorbell,
-- never a durable fact.

ALTER TABLE "mailboxes" ADD COLUMN IF NOT EXISTS "sync_requested_at" timestamp with time zone;
