-- A SECOND TERM ON A SENDER RULE — `rules.subject_contains`, so one sender can be split by subject.
--
-- ══ WHAT THIS FIXES ════════════════════════════════════════════════════════════════════════
--
-- A `rules` row has always been able to say ONE thing about a message: it is from this address, or
-- from this domain, or it carries this header. One sender who sends two kinds of mail therefore has
-- no representation at all — `info@` at a small host is the invoice AND the nightly
-- `[NinjaFirewall]` alert, and a sender rule filing that address to Reads files the invoice with
-- the alerts. The user's actual intent is a CONJUNCTION: *from this address AND with this in the
-- subject*. That is this column.
--
-- ══ NULL IS THE RESTING STATE, AND THERE IS NO BACKFILL ════════════════════════════════════
--
-- NULL means "this rule has no subject term" — the truth for every rule that exists when this
-- lands, and byte-identical to the pre-column router. The data statement that must NEVER appear
-- here is any `UPDATE rules SET subject_contains = …`: a term invented for an existing rule would
-- NARROW a decision its owner made about a whole sender, so mail that has been filing correctly
-- for months would stop matching and silently drift back to the Ohbox. Unlike most of the
-- backfills this journal has refused, this one would not merely be unprovable — it would be
-- actively destructive, and it is un-fixable by a later entry (see the README's rule about
-- corrective migrations).
--
-- ══ WHY ADDING IT CANNOT WIDEN ANYBODY'S ROUTING ═══════════════════════════════════════════
--
-- `packages/core/src/rules.ts#matches` reads the column as an EXTRA term a rule must satisfy,
-- never as an alternative one, so a present term can only make a rule fire LESS often. Two
-- consequences worth writing down:
--
--   · an engine deployed BEHIND this migration keeps matching on the sender alone, which is the
--     pre-column behaviour rather than a bypass — the honest degradation, and the reason deploy
--     order here is about not wasting a deploy rather than about correctness;
--   · a rule with a term can never admit a sender the same rule without one would have refused.
--     Nothing about the consent gate moves.
--
-- The ORDER does move, and that half is in `core/src/rules.ts#compareRules` (mirrored in
-- `drizzle-repo.ts#listRules`' `ORDER BY`), not here: a subject-carrying sender rule outranks a
-- bare sender rule for the same address, because otherwise the more specific of two statements
-- about one sender would win or lose on a UUID tie-break.
--
-- ══ THE CHECK, AND WHY IT IS NOT DECORATION ════════════════════════════════════════════════
--
-- "No subject term" must have exactly ONE representation. Without the CHECK it has three — NULL,
-- `''`, and a whitespace-only string — and every reader (the router, the adapter's `ORDER BY`, the
-- specificity rank, the client's rule list) would have to agree independently about which of them
-- means "absent". They would agree until one of them did not, and the failure would be a rule that
-- matches every subject while its row looks specific.
--
-- ── THE PREDICATE IS A REGEX AND NOT `btrim`, AND THAT IS A MEASUREMENT ────────────────────
--
-- The first draft of this file read `length(btrim(subject_contains)) between 1 and 200`. It is
-- wrong, and the guard caught it: **one-argument `btrim` trims SPACES ONLY.** `btrim(E'\t')` is
-- `E'\t'`, length 1, so a tab-only term passed the CHECK — while `rules.ts#subjectTermOf` read the
-- same value as ABSENT. That is precisely the disagreement the constraint exists to prevent, shipped
-- inside the constraint: SQL would have ranked such a row as specific and the evaluator would then
-- have matched it against every subject.
--
-- So the predicate is `~ '[^ \t\n\r\f\v]'` — "contains at least one character that is not one of
-- those six" — and `subjectTermOf` trims exactly those six rather than calling JavaScript's
-- `String.prototype.trim`, which also strips Unicode whitespace Postgres would keep. Verified
-- against real Postgres over all eleven shapes (the six whitespace characters, `''`, `'x'`,
-- `' x '`, a mixed run, and U+00A0): the SQL predicate and the JavaScript one now agree on every
-- one, and the default `btrim` disagreed on five.
--
-- `length(subject_contains) <= 200` bounds the STORED value rather than the trimmed one — a refusal
-- to store a subject-length haystack as a needle. `RulesService` trims before writing, so the two
-- are the same number for anything the API produces; the longest token this feature is for
-- ("[NinjaFirewall] Alert:") is well under it.
--
-- ══ ADDITIVE, IDEMPOTENT, REPLAY-SAFE ══════════════════════════════════════════════════════
--
-- `ADD COLUMN IF NOT EXISTS`, nullable, no default: a catalog-only change that rewrites no rows
-- and takes no long lock. The CHECK is added under a preceding `DROP CONSTRAINT IF EXISTS` so a
-- journal replay does not raise 42710 on the constraint — the 0037 trap, and the reason this
-- file is three statements rather than two. A partially-applied window costs nothing: a column
-- with no CHECK yet is still only ever written by `RulesService`, which validates the same shape.
--
-- ══ THE `when` IS 1788728086206, AND IT IS NOT max+1 DAY BY ACCIDENT ═══════════════════════
--
-- The README's rule is that `when` must be STRICTLY GREATER than this journal's maximum, because
-- drizzle applies an entry only if `max(created_at) < when` — an entry at or below the maximum is
-- skipped FOREVER, silently. What that rule does not say is the part that bites: **the maximum you
-- have to beat lives in the DATABASE, not in this folder.**
--
-- A test database can already hold journal rows this folder does not describe — a `when` recorded by
-- a file that was never merged, or one recorded ahead of the entry it belongs to. `max + one day`
-- computed from the `.sql` files on disk is then BELOW the recorded maximum, and the new migration is
-- skipped on that database while the objects it was supposed to create are already there from
-- somewhere else. Every `*.pg.test.ts` over it passes, against DDL this file never emitted. Nothing
-- errors, because a skip is how drizzle reports "already applied".
--
-- Hence 1788728086206 rather than the value the files alone suggest, and hence the rule for anyone
-- adding the next entry:
--
--   · pick a value strictly greater than `max(created_at)` in `drizzle_mail.__drizzle_migrations`,
--     not merely greater than the newest `when` in `meta/_journal.json`;
--   · DELETING an unexpected row is not the fix. Whatever wrote it writes it again on its next
--     `runMigrations`, so the collision returns. A larger, unique value survives;
--   · before trusting a green `*.pg.test.ts` for a new migration, check that ITS OWN `when` is in
--     `drizzle_mail.__drizzle_migrations` with a real hash. That single query is the difference
--     between a guard and a coincidence.
--
-- ROLLBACK is `ALTER TABLE rules DROP COLUMN subject_contains` (the CHECK goes with it). The cost
-- is that every subject rule reverts to matching its sender's whole mail — a WIDENING, so the
-- rollback is not silent for the user: mail they had split by subject re-collapses into one pile.
-- Prefer disabling the rules to dropping the column.

ALTER TABLE "rules" ADD COLUMN IF NOT EXISTS "subject_contains" text;
--> statement-breakpoint
ALTER TABLE "rules" DROP CONSTRAINT IF EXISTS "rules_subject_contains_nonempty";
--> statement-breakpoint
ALTER TABLE "rules" ADD CONSTRAINT "rules_subject_contains_nonempty" CHECK ("subject_contains" IS NULL OR ("subject_contains" ~ '[^ \t\n\r\f\v]' AND length("subject_contains") <= 200));
