-- REISSUE of 0066_folders_enabled — same statement, new journal position (review round 2).
--
-- ══ WHY A MIGRATION EXISTS TWICE ═══════════════════════════════════════════════════════════
--
-- 0066's journal entry was first minted BETWEEN two entries another lane had already landed
-- and applied (0067/0068). drizzle's migrator is a single watermark — an entry at or below
-- max(created_at) is skipped FOREVER, silently — so any database that migrated in that window
-- (a local engine that updated between those commits) sits at 0068 with no
-- `folders_enabled_at`, and every whole-row read of `account_settings` answers 42703 across
-- the consent surface.
--
-- The first repair retimed 0066 itself past the maximum. That healed the skip but mutated an
-- already-applied entry, which leaves every database that ran the ORIGINAL entry holding a
-- bookkeeping row the journal no longer describes. So: 0066 keeps its original entry exactly
-- as first shipped, and THIS entry re-runs the same idempotent statement from a position
-- strictly above the journal's maximum. Every class of database ends consistent:
--
--   · fresh replay        — 0066 creates the column, this applies as a no-op;
--   · skipped-0066 window — the watermark is past 0066, this one applies and heals it;
--   · already reissued    — this entry's `when` EQUALS the retimed row such a database
--                           recorded, so it is not applied again and rows match entries.
--
-- ══ ADDITIVE, IDEMPOTENT ═══════════════════════════════════════════════════════════════════
--
-- The one statement is 0066's, verbatim: ADD COLUMN IF NOT EXISTS, nullable, no default, no
-- backfill, no CHECK, no index. Re-running it anywhere is a no-op. Column semantics, deploy
-- order and rollback are documented in 0066_folders_enabled.sql and do not change here.

ALTER TABLE "account_settings" ADD COLUMN IF NOT EXISTS "folders_enabled_at" timestamp with time zone;
