/**
 * THE SQLITE JOURNAL, INLINED — the same files, as a module a device bundler can see.
 *
 * The store on a phone is migrated by the same journal a checkout holds in `drizzle-sqlite/`,
 * and it cannot be READ from there: the bundler that builds the application resolves imports, not
 * directory listings, so a migrator that opened `.sql` files off disk would work in every test
 * and find nothing on a device. The files are therefore compiled into this module.
 *
 * GENERATED FROM THE DIRECTORY, NEVER EDITED. Two copies of the same SQL is exactly the shape
 * that drifts, so `sqlite-journal-inlined.test.ts` reads the directory and compares it with what
 * is here, byte for byte and in order, and fails on any difference — a file added, a file
 * changed, or a file this module still carries after it was removed.
 *
 * Regenerate with `node scripts/gen-sqlite-journal.mjs` after touching the directory.
 */

/** One journal entry: the file it came from and the statements it applies, in order. */
export interface SqliteJournalEntry {
  readonly name: string;
  readonly statements: readonly string[];
}

export const SQLITE_JOURNAL: readonly SqliteJournalEntry[] = [
  {
    "name": "0001_baseline.sql",
    "statements": [
      "CREATE TABLE \"account_settings\" (\n  \"account_id\" text PRIMARY KEY NOT NULL,\n  \"dormancy_days\" integer,\n  \"seed_confirmed_at\" integer,\n  \"seed_confirmed_count\" integer NOT NULL DEFAULT 0,\n  \"seed_declined_count\" integer NOT NULL DEFAULT 0,\n  \"screening_reset_at\" integer,\n  \"auto_suggest_at\" integer,\n  \"ohbox_policy\" text,\n  \"ohbox_bar\" text,\n  \"ohbox_tidy_requested_at\" integer,\n  \"ohbox_tidy_done_at\" integer,\n  \"ohbox_tidy_cursor\" text,\n  \"screener_auto_apply_at\" integer,\n  \"folders_enabled_at\" integer,\n  \"screening_baseline_at\" integer,\n  \"block_remote_images_at\" integer,\n  \"load_tracking_pixels_at\" integer,\n  \"block_auto_unsubscribe_at\" integer,\n  \"locale\" text,\n  \"theme_face\" text,\n  \"onboarding_completed_at\" integer,\n  \"screening_scope\" text NOT NULL DEFAULT 'window',\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))\n);",
      "CREATE TABLE \"account_storage\" (\n  \"account_id\" text PRIMARY KEY NOT NULL,\n  \"bytes\" integer NOT NULL DEFAULT 0,\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"account_storage_bytes_nonneg\" CHECK (\"bytes\" >= 0)\n);",
      "CREATE TABLE \"account_sync_state\" (\n  \"account_id\" text PRIMARY KEY NOT NULL,\n  \"next_seq\" integer NOT NULL DEFAULT 0\n);",
      "CREATE TABLE \"accounts\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"name\" text NOT NULL DEFAULT '',\n  \"ai_enabled\" integer NOT NULL DEFAULT true,\n  \"ai_answered_at\" integer,\n  \"erased_at\" integer,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))\n);",
      "CREATE TABLE \"approvals\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"kind\" text NOT NULL,\n  \"message_id\" text,\n  \"routing_decision_id\" text,\n  \"action\" text NOT NULL,\n  \"summary\" text NOT NULL DEFAULT '',\n  \"payload\" text,\n  \"confidence\" real,\n  \"status\" text NOT NULL DEFAULT 'pending',\n  \"expires_at\" integer,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))\n);",
      "CREATE TABLE \"attachments\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"message_id\" text NOT NULL,\n  \"filename\" text,\n  \"content_type\" text NOT NULL,\n  \"size_bytes\" integer NOT NULL DEFAULT 0,\n  \"part_id\" text,\n  \"content_id\" text,\n  \"inline\" integer NOT NULL DEFAULT false,\n  \"content_sha256\" text,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  FOREIGN KEY (\"message_id\") REFERENCES \"messages\"(\"id\")\n);",
      "CREATE TABLE \"audit_log\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"action\" text NOT NULL,\n  \"payload\" text,\n  \"inverse\" text,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))\n);",
      "CREATE TABLE \"away_replies\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"mailbox_id\" text NOT NULL,\n  \"message_id\" text NOT NULL,\n  \"sender\" text NOT NULL,\n  \"outcome\" text NOT NULL,\n  \"reason\" text,\n  \"text_hash\" text,\n  \"minted_message_id\" text,\n  \"decided_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"sent_at\" integer\n);",
      "CREATE TABLE \"away_responder_sent\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"sender\" text NOT NULL,\n  \"responder_updated_at\" integer NOT NULL,\n  \"message_id\" text,\n  \"minted_message_id\" text,\n  \"sent_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))\n);",
      "CREATE TABLE \"away_responders\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"enabled\" integer NOT NULL DEFAULT false,\n  \"subject\" text,\n  \"body\" text,\n  \"starts_at\" integer,\n  \"ends_at\" integer,\n  \"audience\" text NOT NULL DEFAULT 'screened_in',\n  \"throttle\" text NOT NULL DEFAULT 'per_day',\n  \"enabled_at\" integer,\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"away_responders_account_id_unique\" UNIQUE (\"account_id\")\n);",
      "CREATE TABLE \"away_sender_state\" (\n  \"account_id\" text NOT NULL,\n  \"sender\" text NOT NULL,\n  \"last_replied_at\" integer NOT NULL,\n  \"last_text_hash\" text NOT NULL,\n  CONSTRAINT \"away_sender_state_account_id_sender_pk\" PRIMARY KEY (\"account_id\", \"sender\")\n);",
      "CREATE TABLE \"change_log\" (\n  \"account_id\" text NOT NULL,\n  \"seq\" integer NOT NULL,\n  \"entity_type\" text NOT NULL,\n  \"entity_id\" text NOT NULL,\n  \"op\" text NOT NULL,\n  \"meta\" text,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"change_log_account_id_seq_pk\" PRIMARY KEY (\"account_id\", \"seq\")\n);",
      "CREATE TABLE \"contact_notes\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"contact_id\" text NOT NULL,\n  \"body\" text NOT NULL,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  FOREIGN KEY (\"contact_id\") REFERENCES \"contacts\"(\"id\")\n);",
      "CREATE TABLE \"contacts\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"address\" text NOT NULL,\n  \"name\" text,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"contacts_account_id_address_unique\" UNIQUE (\"account_id\", \"address\")\n);",
      "CREATE TABLE \"devices\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"user_id\" text NOT NULL,\n  \"kind\" text NOT NULL,\n  \"label\" text NOT NULL DEFAULT '',\n  \"ip\" text NOT NULL DEFAULT '',\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"last_seen_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"last_synced_at\" integer,\n  FOREIGN KEY (\"user_id\") REFERENCES \"users\"(\"id\")\n);",
      "CREATE TABLE \"drafts\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"mailbox_id\" text NOT NULL,\n  \"thread_id\" text,\n  \"in_reply_to_message_id\" text,\n  \"subject\" text NOT NULL DEFAULT '',\n  \"body\" text NOT NULL DEFAULT '',\n  \"html\" text,\n  \"to\" text NOT NULL DEFAULT '[]',\n  \"cc\" text NOT NULL DEFAULT '[]',\n  \"bcc\" text NOT NULL DEFAULT '[]',\n  \"rationale\" text,\n  \"status\" text NOT NULL DEFAULT 'draft',\n  \"workflow_dedup_key\" text,\n  \"send_at\" integer,\n  \"send_key\" text,\n  \"send_error\" text,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"drafts_workflow_dedup_key_unique\" UNIQUE (\"workflow_dedup_key\"),\n  FOREIGN KEY (\"mailbox_id\") REFERENCES \"mailboxes\"(\"id\"),\n  FOREIGN KEY (\"thread_id\") REFERENCES \"threads\"(\"id\"),\n  FOREIGN KEY (\"in_reply_to_message_id\") REFERENCES \"messages\"(\"id\")\n);",
      "CREATE TABLE \"flag_state\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"message_id\" text NOT NULL,\n  \"desired_seen\" integer NOT NULL,\n  \"observed_seen\" integer NOT NULL,\n  \"last_set_by\" text NOT NULL,\n  \"reconcile_status\" text NOT NULL DEFAULT 'pending',\n  \"conflict\" integer NOT NULL DEFAULT false,\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"attempts\" integer NOT NULL DEFAULT 0,\n  \"next_attempt_at\" integer,\n  CONSTRAINT \"flag_state_message_id_unique\" UNIQUE (\"message_id\"),\n  FOREIGN KEY (\"message_id\") REFERENCES \"messages\"(\"id\")\n);",
      "CREATE TABLE \"folder_ops\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"mailbox_id\" text NOT NULL,\n  \"folder_id\" text NOT NULL,\n  \"op\" text NOT NULL,\n  \"to_folder\" text,\n  \"status\" text NOT NULL DEFAULT 'pending',\n  \"error\" text,\n  \"attempts\" integer NOT NULL DEFAULT 0,\n  \"requested_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"folder_ops_folder_id_unique\" UNIQUE (\"folder_id\"),\n  FOREIGN KEY (\"mailbox_id\") REFERENCES \"mailboxes\"(\"id\"),\n  FOREIGN KEY (\"folder_id\") REFERENCES \"mailbox_folders\"(\"id\") ON DELETE cascade\n);",
      "CREATE TABLE \"folder_state\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"message_id\" text NOT NULL,\n  \"desired_folder\" text NOT NULL,\n  \"observed_folder\" text NOT NULL,\n  \"last_set_by\" text NOT NULL,\n  \"reconcile_status\" text NOT NULL DEFAULT 'pending',\n  \"conflict\" integer NOT NULL DEFAULT false,\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"attempts\" integer NOT NULL DEFAULT 0,\n  \"next_attempt_at\" integer,\n  CONSTRAINT \"folder_state_message_id_unique\" UNIQUE (\"message_id\"),\n  FOREIGN KEY (\"message_id\") REFERENCES \"messages\"(\"id\")\n);",
      "CREATE TABLE \"graduations\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"pattern_key\" text NOT NULL,\n  \"action\" text NOT NULL DEFAULT 'route',\n  \"positives\" integer NOT NULL DEFAULT 0,\n  \"negatives\" integer NOT NULL DEFAULT 0,\n  \"graduated\" integer NOT NULL DEFAULT false,\n  \"graduated_at\" integer,\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"graduations_account_id_pattern_key_action_unique\" UNIQUE (\"account_id\", \"pattern_key\", \"action\")\n);",
      "CREATE TABLE \"idempotency_keys\" (\n  \"account_id\" text NOT NULL,\n  \"key\" text NOT NULL,\n  \"request_hash\" text NOT NULL,\n  \"response_status\" integer NOT NULL,\n  \"response_json\" text NOT NULL,\n  \"seq\" integer,\n  \"expires_at\" integer NOT NULL,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"idempotency_keys_account_id_key_pk\" PRIMARY KEY (\"account_id\", \"key\")\n);",
      "CREATE TABLE \"kb_entries\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"title\" text NOT NULL,\n  \"content\" text NOT NULL,\n  \"tags\" text NOT NULL DEFAULT '[]',\n  \"workflow_dedup_key\" text,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"kb_entries_workflow_dedup_key_unique\" UNIQUE (\"workflow_dedup_key\")\n);",
      "CREATE TABLE \"learning_signals\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"triggering_action_id\" text NOT NULL,\n  \"kind\" text NOT NULL,\n  \"sender_address\" text,\n  \"sender_domain\" text,\n  \"destination\" text,\n  \"label\" text NOT NULL,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"learning_signals_account_id_triggering_action_id_unique\" UNIQUE (\"account_id\", \"triggering_action_id\")\n);",
      "CREATE TABLE \"mailbox_credentials\" (\n  \"mailbox_id\" text NOT NULL,\n  \"transport\" text NOT NULL,\n  \"secret_enc\" text NOT NULL,\n  \"key_version\" integer NOT NULL,\n  \"meta\" text,\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"mailbox_credentials_mailbox_id_transport_pk\" PRIMARY KEY (\"mailbox_id\", \"transport\"),\n  FOREIGN KEY (\"mailbox_id\") REFERENCES \"mailboxes\"(\"id\")\n);",
      "CREATE TABLE \"mailbox_folders\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"mailbox_id\" text NOT NULL,\n  \"folder\" text NOT NULL,\n  \"uidvalidity\" integer,\n  \"uidnext\" integer,\n  \"highestmodseq\" integer,\n  \"delta_token\" text,\n  \"server_exists\" integer,\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"mailbox_folders_mailbox_id_folder_unique\" UNIQUE (\"mailbox_id\", \"folder\"),\n  FOREIGN KEY (\"mailbox_id\") REFERENCES \"mailboxes\"(\"id\")\n);",
      "CREATE TABLE \"mailboxes\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"provider\" text NOT NULL,\n  \"address\" text NOT NULL,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"display_name\" text,\n  \"status\" text NOT NULL DEFAULT 'connected',\n  \"last_sync_at\" integer,\n  \"auth_kind\" text NOT NULL DEFAULT 'password',\n  \"error_code\" text,\n  \"error_detail\" text,\n  \"failed_at\" integer,\n  \"retry_count\" integer NOT NULL DEFAULT 0,\n  \"retry_after\" integer,\n  \"kickstart_at\" integer,\n  \"disabled_reason\" text,\n  \"takeover_authorized_at\" integer,\n  \"organizer_role\" text NOT NULL DEFAULT 'organizer',\n  \"organized_by_kind\" text,\n  \"organized_by_name\" text,\n  \"organized_by_install_id\" text,\n  \"organized_since\" integer,\n  \"organizer_state\" text,\n  \"organized_by_capabilities\" text,\n  \"organize_consented_at\" integer,\n  \"organizer_event_at\" integer,\n  \"organizer_event_seen_at\" integer,\n  \"release_requested_at\" integer,\n  \"organizer_released_at\" integer,\n  \"junk_folder\" text,\n  \"trash_folder\" text,\n  \"folders_disabled_at\" integer,\n  \"signature\" text,\n  \"junk_sweep_requested_at\" integer,\n  \"inbound_quiet_since\" integer,\n  \"inbound_quiet_dismissed_at\" integer,\n  \"sync_blocked_reason\" text,\n  \"sync_blocked_since\" integer,\n  \"sync_requested_at\" integer,\n  \"smtp_max_size_bytes\" integer,\n  \"smtp_size_probed_at\" integer,\n  \"smtp_size_probe_code\" text,\n  \"sensitive_rescreen_at\" integer,\n  \"sensitive_rescreen_cursor\" text,\n  \"sensitive_rescreen_started_at\" integer,\n  \"sensitive_fp_backfill_at\" integer,\n  \"initial_import_completed_at\" integer,\n  CONSTRAINT \"mailboxes_disabled_reason_closed\" CHECK (\"disabled_reason\" is null or \"disabled_reason\" in ('organized_elsewhere:cloud', 'organized_elsewhere:local', 'organized_elsewhere:mobile', 'organized_elsewhere:unknown')),\n  CONSTRAINT \"mailboxes_sync_blocked_reason_closed\" CHECK (\"sync_blocked_reason\" is null or \"sync_blocked_reason\" in ('lease_unreadable', 'awaiting_credentials', 'at_capacity', 'read_limited')),\n  CONSTRAINT \"mailboxes_organizer_role_closed\" CHECK (\"organizer_role\" in ('organizer', 'reader')),\n  CONSTRAINT \"mailboxes_organized_by_kind_closed\" CHECK (\"organized_by_kind\" is null or \"organized_by_kind\" in ('cloud', 'local', 'mobile', 'unknown')),\n  CONSTRAINT \"mailboxes_organizer_state_closed\" CHECK (\"organizer_state\" is null or \"organizer_state\" in ('held', 'stopped'))\n);",
      "CREATE TABLE \"message_bodies\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"message_id\" text NOT NULL,\n  \"text\" text NOT NULL DEFAULT '',\n  \"html\" text,\n  \"headers\" text NOT NULL DEFAULT '{}',\n  \"loaded_remote_content\" integer NOT NULL DEFAULT false,\n  \"withheld_reason\" text,\n  CONSTRAINT \"message_bodies_message_id_unique\" UNIQUE (\"message_id\"),\n  CONSTRAINT \"message_bodies_html_cap\" CHECK (octet_length(\"html\") <= 262144),\n  FOREIGN KEY (\"message_id\") REFERENCES \"messages\"(\"id\")\n);",
      "CREATE TABLE \"message_failures\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"mailbox_id\" text NOT NULL,\n  \"folder\" text NOT NULL,\n  \"uidvalidity\" integer NOT NULL,\n  \"uid\" integer NOT NULL,\n  \"code\" text NOT NULL,\n  \"attempts\" integer NOT NULL DEFAULT 0,\n  \"attempted_version\" text,\n  \"first_failed_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"last_failed_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"next_attempt_at\" integer,\n  \"resolved_at\" integer,\n  CONSTRAINT \"message_failures_locator_uq\" UNIQUE (\"mailbox_id\", \"folder\", \"uidvalidity\", \"uid\"),\n  FOREIGN KEY (\"mailbox_id\") REFERENCES \"mailboxes\"(\"id\")\n);",
      "CREATE TABLE \"message_instances\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"mailbox_id\" text NOT NULL,\n  \"message_id\" text NOT NULL,\n  \"folder\" text NOT NULL,\n  \"uidvalidity\" integer NOT NULL,\n  \"uid\" integer NOT NULL,\n  \"is_primary\" integer NOT NULL DEFAULT false,\n  \"first_seen_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"last_seen_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"message_instances_locator_uq\" UNIQUE (\"mailbox_id\", \"folder\", \"uidvalidity\", \"uid\"),\n  FOREIGN KEY (\"mailbox_id\") REFERENCES \"mailboxes\"(\"id\"),\n  FOREIGN KEY (\"message_id\") REFERENCES \"messages\"(\"id\")\n);",
      "CREATE TABLE \"message_states\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"message_id\" text NOT NULL,\n  \"state\" text NOT NULL DEFAULT 'none',\n  \"bubble_up_at\" integer,\n  \"set_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"message_states_message_id_unique\" UNIQUE (\"message_id\"),\n  FOREIGN KEY (\"message_id\") REFERENCES \"messages\"(\"id\")\n);",
      "CREATE TABLE \"message_tags\" (\n  \"account_id\" text NOT NULL,\n  \"message_id\" text NOT NULL,\n  \"tag_id\" text NOT NULL,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"message_tags_message_id_tag_id_pk\" PRIMARY KEY (\"message_id\", \"tag_id\"),\n  FOREIGN KEY (\"message_id\") REFERENCES \"messages\"(\"id\"),\n  FOREIGN KEY (\"tag_id\") REFERENCES \"tags\"(\"id\")\n);",
      "CREATE TABLE \"messages\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"mailbox_id\" text NOT NULL,\n  \"message_id_header\" text,\n  \"body_hash\" text NOT NULL,\n  \"dedup_key\" text NOT NULL,\n  \"subject\" text NOT NULL DEFAULT '',\n  \"from_address\" text NOT NULL DEFAULT '',\n  \"from_name\" text,\n  \"date\" integer,\n  \"native_locator\" text,\n  \"no_ai\" integer NOT NULL DEFAULT false,\n  \"no_forward\" integer NOT NULL DEFAULT false,\n  \"no_kb\" integer NOT NULL DEFAULT false,\n  \"priority\" integer NOT NULL DEFAULT false,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"thread_id\" text,\n  \"unread\" integer NOT NULL DEFAULT true,\n  \"last_read_at\" integer,\n  \"deleted_at\" integer,\n  \"snippet\" text NOT NULL DEFAULT '',\n  \"to_addresses\" text NOT NULL DEFAULT '[]',\n  \"cc_addresses\" text NOT NULL DEFAULT '[]',\n  \"has_attachments\" integer NOT NULL DEFAULT false,\n  \"attachment_count\" integer NOT NULL DEFAULT 0,\n  \"sensitivity_category\" text,\n  \"auth_verdict\" text,\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"messages_mailbox_id_dedup_key_unique\" UNIQUE (\"mailbox_id\", \"dedup_key\"),\n  FOREIGN KEY (\"mailbox_id\") REFERENCES \"mailboxes\"(\"id\"),\n  FOREIGN KEY (\"thread_id\") REFERENCES \"threads\"(\"id\")\n);",
      "CREATE TABLE \"notify_rules\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"target\" text NOT NULL,\n  \"kind\" text NOT NULL DEFAULT 'sender',\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))\n);",
      "CREATE TABLE \"organizer_requests\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"mailbox_id\" text NOT NULL,\n  \"kind\" text NOT NULL,\n  \"payload\" text NOT NULL,\n  \"decided_at\" integer NOT NULL,\n  \"state\" text NOT NULL DEFAULT 'pending',\n  \"sent_at\" integer,\n  \"resolved_at\" integer,\n  \"refused_reason\" text,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))\n);",
      "CREATE TABLE \"outbound_sends\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"idempotency_key\" text NOT NULL,\n  \"draft_id\" text NOT NULL,\n  \"minted_message_id\" text NOT NULL,\n  \"provider_message_id\" text,\n  \"status\" text NOT NULL DEFAULT 'pending',\n  \"sent_at\" integer,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"outbound_sends_account_id_idempotency_key_unique\" UNIQUE (\"account_id\", \"idempotency_key\"),\n  FOREIGN KEY (\"draft_id\") REFERENCES \"drafts\"(\"id\")\n);",
      "CREATE TABLE \"pairing_tokens\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"created_by_user_id\" text,\n  \"grant\" text NOT NULL,\n  \"token_hash\" text NOT NULL,\n  \"label\" text NOT NULL DEFAULT '',\n  \"expires_at\" integer NOT NULL,\n  \"consumed_at\" integer,\n  \"revoked_at\" integer,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"pairing_tokens_token_hash_unique\" UNIQUE (\"token_hash\"),\n  FOREIGN KEY (\"created_by_user_id\") REFERENCES \"users\"(\"id\")\n);",
      "CREATE TABLE \"refresh_tokens\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"user_id\" text NOT NULL,\n  \"session_id\" text NOT NULL,\n  \"family_id\" text NOT NULL,\n  \"token_hash\" text NOT NULL,\n  \"expires_at\" integer NOT NULL,\n  \"consumed_at\" integer,\n  \"revoked_at\" integer,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"refresh_tokens_token_hash_unique\" UNIQUE (\"token_hash\"),\n  FOREIGN KEY (\"user_id\") REFERENCES \"users\"(\"id\"),\n  FOREIGN KEY (\"session_id\") REFERENCES \"sessions\"(\"id\")\n);",
      "CREATE TABLE \"routing_decisions\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"message_id\" text NOT NULL,\n  \"input_provenance\" text NOT NULL,\n  \"matched_rule_id\" text,\n  \"destination\" text NOT NULL,\n  \"confidence\" real,\n  \"rationale\" text,\n  \"spam\" integer NOT NULL DEFAULT false,\n  \"status\" text NOT NULL,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  FOREIGN KEY (\"message_id\") REFERENCES \"messages\"(\"id\")\n);",
      "CREATE TABLE \"rules\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"kind\" text NOT NULL,\n  \"match\" text NOT NULL,\n  \"destination\" text NOT NULL,\n  \"priority\" integer NOT NULL DEFAULT 0,\n  \"provenance\" text NOT NULL DEFAULT 'manual',\n  \"enabled\" integer NOT NULL DEFAULT true,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"hits\" integer NOT NULL DEFAULT 0,\n  \"last_hit_at\" integer,\n  \"demotions\" integer NOT NULL DEFAULT 0,\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"retro_requested_at\" integer,\n  \"retro_done_at\" integer,\n  \"retro_cursor\" text,\n  \"retro_moved\" integer NOT NULL DEFAULT 0,\n  \"subject_contains\" text,\n  \"body_contains\" text\n);",
      "CREATE TABLE \"sessions\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"user_id\" text NOT NULL,\n  \"device_id\" text,\n  \"family_id\" text NOT NULL,\n  \"access_token_hash\" text,\n  \"scope\" text NOT NULL DEFAULT 'full',\n  \"access_expires_at\" integer NOT NULL,\n  \"refresh_expires_at\" integer NOT NULL,\n  \"last_twofa_at\" integer,\n  \"revoked_at\" integer,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"last_seen_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"last_synced_at\" integer,\n  FOREIGN KEY (\"user_id\") REFERENCES \"users\"(\"id\"),\n  FOREIGN KEY (\"device_id\") REFERENCES \"devices\"(\"id\")\n);",
      "CREATE TABLE \"snippets\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"title\" text NOT NULL,\n  \"body\" text NOT NULL,\n  \"shortcut\" text,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))\n);",
      "CREATE TABLE \"tags\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"name\" text NOT NULL,\n  \"hue\" text NOT NULL DEFAULT 'moss',\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))\n);",
      "CREATE TABLE \"thread_notes\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"thread_id\" text NOT NULL,\n  \"body\" text NOT NULL,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  FOREIGN KEY (\"thread_id\") REFERENCES \"threads\"(\"id\")\n);",
      "CREATE TABLE \"threads\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"subject\" text NOT NULL DEFAULT '',\n  \"participants\" text NOT NULL DEFAULT '[]',\n  \"last_message_at\" integer,\n  \"muted\" integer NOT NULL DEFAULT false,\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"root_message_id_header\" text\n);",
      "CREATE TABLE \"tracker_events\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"message_id\" text NOT NULL,\n  \"kind\" text NOT NULL,\n  \"tracker_host\" text,\n  \"url\" text,\n  \"detected_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  FOREIGN KEY (\"message_id\") REFERENCES \"messages\"(\"id\")\n);",
      "CREATE TABLE \"unsubscribe_records\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"mailbox_id\" text NOT NULL,\n  \"list_key\" text NOT NULL,\n  \"state\" text NOT NULL,\n  \"refusal\" text,\n  \"http_status\" integer,\n  \"message_id\" text NOT NULL,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  FOREIGN KEY (\"mailbox_id\") REFERENCES \"mailboxes\"(\"id\"),\n  FOREIGN KEY (\"message_id\") REFERENCES \"messages\"(\"id\")\n);",
      "CREATE TABLE \"users\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"email\" text NOT NULL,\n  \"display_name\" text NOT NULL DEFAULT '',\n  \"email_verified_at\" integer,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"users_account_id_email_unique\" UNIQUE (\"account_id\", \"email\"),\n  FOREIGN KEY (\"account_id\") REFERENCES \"accounts\"(\"id\")\n);",
      "CREATE TABLE \"workflow_proposals\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"name\" text NOT NULL,\n  \"rationale\" text NOT NULL DEFAULT '',\n  \"trigger\" text NOT NULL DEFAULT '{}',\n  \"steps\" text NOT NULL DEFAULT '[]',\n  \"source_pattern\" text,\n  \"status\" text NOT NULL DEFAULT 'open',\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))\n);",
      "CREATE TABLE \"workflow_runs\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"workflow_id\" text,\n  \"status\" text NOT NULL DEFAULT 'pending',\n  \"trigger\" text NOT NULL DEFAULT '{}',\n  \"log\" text NOT NULL DEFAULT '[]',\n  \"step_cursor\" integer NOT NULL DEFAULT 0,\n  \"reason\" text,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"finished_at\" integer,\n  \"claimed_at\" integer,\n  FOREIGN KEY (\"workflow_id\") REFERENCES \"workflows\"(\"id\")\n);",
      "CREATE TABLE \"workflows\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"name\" text NOT NULL,\n  \"trigger\" text NOT NULL DEFAULT '{}',\n  \"steps\" text NOT NULL DEFAULT '[]',\n  \"enabled\" integer NOT NULL DEFAULT false,\n  \"provenance\" text NOT NULL DEFAULT 'user',\n  \"deleted_at\" integer,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"updated_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))\n);",
      "CREATE INDEX \"approvals_account_status_idx\" ON \"approvals\" (\"account_id\", \"status\");",
      "CREATE INDEX \"attachments_account_message_idx\" ON \"attachments\" (\"account_id\", \"message_id\");",
      "CREATE UNIQUE INDEX \"away_replies_message_uq\" ON \"away_replies\" (\"account_id\", \"message_id\");",
      "CREATE INDEX \"away_replies_sender_idx\" ON \"away_replies\" (\"account_id\", \"sender\", \"decided_at\");",
      "CREATE UNIQUE INDEX \"away_responder_sent_episode_uq\" ON \"away_responder_sent\" (\"account_id\", \"sender\", \"responder_updated_at\");",
      "CREATE INDEX \"away_responder_sent_account_idx\" ON \"away_responder_sent\" (\"account_id\");",
      "CREATE INDEX \"change_log_move_to_inbox_idx\" ON \"change_log\" (\"account_id\", \"entity_id\") WHERE \"op\" = 'move' and \"meta\" ->> 'to' = 'INBOX';",
      "CREATE INDEX \"contact_notes_account_contact_idx\" ON \"contact_notes\" (\"account_id\", \"contact_id\");",
      "CREATE INDEX \"devices_user_idx\" ON \"devices\" (\"user_id\");",
      "CREATE INDEX \"drafts_account_updated_idx\" ON \"drafts\" (\"account_id\", \"updated_at\");",
      "CREATE INDEX \"drafts_scheduled_due_idx\" ON \"drafts\" (\"send_at\") WHERE \"status\" = 'scheduled';",
      "CREATE INDEX \"kb_entries_account_idx\" ON \"kb_entries\" (\"account_id\");",
      "CREATE INDEX \"learning_signals_account_idx\" ON \"learning_signals\" (\"account_id\");",
      "CREATE UNIQUE INDEX \"mailboxes_active_address_uq\" ON \"mailboxes\" (\"account_id\", lower(\"address\")) WHERE \"status\" <> 'disabled';",
      "CREATE INDEX \"message_bodies_withheld_idx\" ON \"message_bodies\" (\"withheld_reason\", \"message_id\") WHERE \"withheld_reason\" is not null;",
      "CREATE INDEX \"message_instances_message_idx\" ON \"message_instances\" (\"message_id\");",
      "CREATE INDEX \"message_states_account_state_idx\" ON \"message_states\" (\"account_id\", \"state\");",
      "CREATE INDEX \"message_tags_account_message_idx\" ON \"message_tags\" (\"account_id\", \"message_id\");",
      "CREATE INDEX \"message_tags_tag_idx\" ON \"message_tags\" (\"tag_id\");",
      "CREATE INDEX \"messages_account_thread_idx\" ON \"messages\" (\"account_id\", \"thread_id\");",
      "CREATE INDEX \"messages_account_message_id_header_idx\" ON \"messages\" (\"account_id\", \"message_id_header\");",
      "CREATE INDEX \"messages_account_mailbox_unread_idx\" ON \"messages\" (\"account_id\", \"mailbox_id\", \"unread\");",
      "CREATE INDEX \"messages_account_from_addr_idx\" ON \"messages\" (\"account_id\", lower(\"from_address\"), \"id\");",
      "CREATE INDEX \"messages_account_from_domain_idx\" ON \"messages\" (\"account_id\", substr(lower(\"from_address\"), instr(lower(\"from_address\"), '@') + 1), \"id\");",
      "CREATE INDEX \"notify_rules_account_idx\" ON \"notify_rules\" (\"account_id\");",
      "CREATE INDEX \"organizer_requests_mailbox_state_idx\" ON \"organizer_requests\" (\"mailbox_id\", \"state\");",
      "CREATE INDEX \"organizer_requests_account_state_idx\" ON \"organizer_requests\" (\"account_id\", \"state\");",
      "CREATE INDEX \"refresh_tokens_family_idx\" ON \"refresh_tokens\" (\"family_id\");",
      "CREATE INDEX \"refresh_tokens_session_idx\" ON \"refresh_tokens\" (\"session_id\");",
      "CREATE INDEX \"routing_decisions_account_message_idx\" ON \"routing_decisions\" (\"account_id\", \"message_id\");",
      "CREATE INDEX \"rules_retro_owed_idx\" ON \"rules\" (\"account_id\") WHERE \"retro_requested_at\" is not null and \"retro_done_at\" is null;",
      "CREATE INDEX \"sessions_user_idx\" ON \"sessions\" (\"user_id\");",
      "CREATE INDEX \"sessions_family_idx\" ON \"sessions\" (\"family_id\");",
      "CREATE INDEX \"sessions_access_token_hash_idx\" ON \"sessions\" (\"access_token_hash\");",
      "CREATE INDEX \"snippets_account_idx\" ON \"snippets\" (\"account_id\");",
      "CREATE UNIQUE INDEX \"tags_account_name_uq\" ON \"tags\" (\"account_id\", lower(\"name\"));",
      "CREATE INDEX \"thread_notes_account_thread_idx\" ON \"thread_notes\" (\"account_id\", \"thread_id\");",
      "CREATE INDEX \"threads_account_last_message_idx\" ON \"threads\" (\"account_id\", \"last_message_at\");",
      "CREATE UNIQUE INDEX \"threads_account_root_header_uq\" ON \"threads\" (\"account_id\", \"root_message_id_header\");",
      "CREATE INDEX \"tracker_events_account_message_idx\" ON \"tracker_events\" (\"account_id\", \"message_id\");",
      "CREATE INDEX \"tracker_events_account_detected_idx\" ON \"tracker_events\" (\"account_id\", \"detected_at\");",
      "CREATE UNIQUE INDEX \"unsubscribe_records_mailbox_list_uq\" ON \"unsubscribe_records\" (\"mailbox_id\", \"list_key\");",
      "CREATE INDEX \"unsubscribe_records_account_idx\" ON \"unsubscribe_records\" (\"account_id\");",
      "CREATE UNIQUE INDEX \"users_email_unique_idx\" ON \"users\" (\"email\");",
      "CREATE INDEX \"workflow_proposals_account_status_idx\" ON \"workflow_proposals\" (\"account_id\", \"status\");",
      "CREATE INDEX \"workflow_runs_account_status_idx\" ON \"workflow_runs\" (\"account_id\", \"status\");",
      "CREATE INDEX \"workflows_account_idx\" ON \"workflows\" (\"account_id\");",
      "CREATE VIRTUAL TABLE messages_fts USING fts5(\n  subject, from_address,\n  content='messages',\n  content_rowid='rowid',\n  tokenize='unicode61 remove_diacritics 2'\n);",
      "CREATE TRIGGER messages_fts_after_insert AFTER INSERT ON messages BEGIN\n  INSERT INTO messages_fts(rowid, subject, from_address) VALUES (new.rowid, new.subject, new.from_address);\nEND;",
      "CREATE TRIGGER messages_fts_after_delete AFTER DELETE ON messages BEGIN\n  INSERT INTO messages_fts(messages_fts, rowid, subject, from_address) VALUES ('delete', old.rowid, old.subject, old.from_address);\nEND;",
      "CREATE TRIGGER messages_fts_after_update AFTER UPDATE ON messages BEGIN\n  INSERT INTO messages_fts(messages_fts, rowid, subject, from_address) VALUES ('delete', old.rowid, old.subject, old.from_address);\n  INSERT INTO messages_fts(rowid, subject, from_address) VALUES (new.rowid, new.subject, new.from_address);\nEND;",
      "CREATE VIRTUAL TABLE message_bodies_fts USING fts5(\n  text,\n  content='message_bodies',\n  content_rowid='rowid',\n  tokenize='unicode61 remove_diacritics 2'\n);",
      "CREATE TRIGGER message_bodies_fts_after_insert AFTER INSERT ON message_bodies BEGIN\n  INSERT INTO message_bodies_fts(rowid, text) VALUES (new.rowid, new.text);\nEND;",
      "CREATE TRIGGER message_bodies_fts_after_delete AFTER DELETE ON message_bodies BEGIN\n  INSERT INTO message_bodies_fts(message_bodies_fts, rowid, text) VALUES ('delete', old.rowid, old.text);\nEND;",
      "CREATE TRIGGER message_bodies_fts_after_update AFTER UPDATE ON message_bodies BEGIN\n  INSERT INTO message_bodies_fts(message_bodies_fts, rowid, text) VALUES ('delete', old.rowid, old.text);\n  INSERT INTO message_bodies_fts(rowid, text) VALUES (new.rowid, new.text);\nEND;",
      "CREATE VIRTUAL TABLE kb_entries_fts USING fts5(\n  title, content,\n  content='kb_entries',\n  content_rowid='rowid',\n  tokenize='unicode61 remove_diacritics 2'\n);",
      "CREATE TRIGGER kb_entries_fts_after_insert AFTER INSERT ON kb_entries BEGIN\n  INSERT INTO kb_entries_fts(rowid, title, content) VALUES (new.rowid, new.title, new.content);\nEND;",
      "CREATE TRIGGER kb_entries_fts_after_delete AFTER DELETE ON kb_entries BEGIN\n  INSERT INTO kb_entries_fts(kb_entries_fts, rowid, title, content) VALUES ('delete', old.rowid, old.title, old.content);\nEND;",
      "CREATE TRIGGER kb_entries_fts_after_update AFTER UPDATE ON kb_entries BEGIN\n  INSERT INTO kb_entries_fts(kb_entries_fts, rowid, title, content) VALUES ('delete', old.rowid, old.title, old.content);\n  INSERT INTO kb_entries_fts(rowid, title, content) VALUES (new.rowid, new.title, new.content);\nEND;"
    ]
  },
  {
    "name": "0093_outbound_send_fingerprints.sql",
    "statements": [
      "CREATE TABLE \"outbound_send_fingerprints\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"mailbox_id\" text NOT NULL,\n  \"fingerprint\" text NOT NULL,\n  \"send_id\" text NOT NULL REFERENCES \"outbound_sends\"(\"id\") ON DELETE CASCADE,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  CONSTRAINT \"outbound_send_fingerprints_content_uq\" UNIQUE (\"account_id\", \"mailbox_id\", \"fingerprint\"),\n  CONSTRAINT \"outbound_send_fingerprints_hex\" CHECK (length(\"fingerprint\") = 64 AND \"fingerprint\" NOT GLOB '*[^0-9a-f]*')\n);"
    ]
  },
  {
    "name": "0094_request_kinds_moves_profile.sql",
    "statements": [
      "CREATE TABLE \"mailbox_profile_mirror\" (\n  \"mailbox_id\" text PRIMARY KEY NOT NULL,\n  \"account_id\" text NOT NULL,\n  \"uidvalidity\" integer,\n  \"uid\" integer,\n  \"doc\" text NOT NULL,\n  \"read_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER))\n);",
      "CREATE INDEX \"mailbox_profile_mirror_account_idx\" ON \"mailbox_profile_mirror\" (\"account_id\");"
    ]
  },
  {
    "name": "0095_outbound_send_resolution.sql",
    "statements": [
      "CREATE TABLE \"outbound_sends__0095\" (\n  \"id\" text PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' ||\n  substr(lower(hex(randomblob(2))), 2) || '-' ||\n  substr('89ab', 1 + (abs(random()) % 4), 1) ||\n  substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),\n  \"account_id\" text NOT NULL,\n  \"idempotency_key\" text NOT NULL,\n  \"draft_id\" text,\n  \"minted_message_id\" text NOT NULL,\n  \"provider_message_id\" text,\n  \"status\" text NOT NULL DEFAULT 'pending',\n  \"sent_at\" integer,\n  \"created_at\" integer NOT NULL DEFAULT (CAST(unixepoch('subsec') * 1000 AS INTEGER)),\n  \"resolved_by\" text,\n  \"resolved_at\" integer,\n  CONSTRAINT \"outbound_sends_account_id_idempotency_key_unique\" UNIQUE (\"account_id\", \"idempotency_key\"),\n  FOREIGN KEY (\"draft_id\") REFERENCES \"drafts\"(\"id\") ON DELETE SET NULL\n);",
      "INSERT INTO \"outbound_sends__0095\"\n  (\"id\", \"account_id\", \"idempotency_key\", \"draft_id\", \"minted_message_id\",\n   \"provider_message_id\", \"status\", \"sent_at\", \"created_at\")\nSELECT \"id\", \"account_id\", \"idempotency_key\", \"draft_id\", \"minted_message_id\",\n       \"provider_message_id\", \"status\", \"sent_at\", \"created_at\"\n  FROM \"outbound_sends\";",
      "DROP TABLE \"outbound_sends\";",
      "ALTER TABLE \"outbound_sends__0095\" RENAME TO \"outbound_sends\";"
    ]
  },
  {
    "name": "0096_away_piles.sql",
    "statements": [
      "ALTER TABLE \"away_responders\" ADD COLUMN \"piles\" text NOT NULL DEFAULT '[\"INBOX\"]';",
      "ALTER TABLE \"away_sender_state\" ADD COLUMN \"undeliverable_at\" integer;"
    ]
  },
  {
    "name": "0097_folder_state_last_error_class.sql",
    "statements": [
      "ALTER TABLE \"folder_state\" ADD COLUMN \"last_error_class\" text;"
    ]
  },
  {
    "name": "0098_signature_html.sql",
    "statements": [
      "ALTER TABLE \"mailboxes\" ADD COLUMN \"signature_html\" text;"
    ]
  },
  {
    "name": "0099_folder_state_trashed_from.sql",
    "statements": [
      "ALTER TABLE \"folder_state\" ADD COLUMN \"trashed_from\" text;"
    ]
  }
] as const;
